apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yamtrack.fullname" . }}
  labels:
    {{- include "yamtrack.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{- if not (kindIs "invalid" $value) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
